<?xml version="1.0" encoding="utf-8"?><Database Name="CandidateTracker" Class="CandidateTrackerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=CandidateTracker;Integrated Security=True" SettingsObjectName="CandidateTracker.data.Properties.Settings" SettingsPropertyName="CandidateTrackerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Candidates" Member="Candidates">
    <Type Name="Candidate">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="Status" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>